android: use cargo test instead of nextest
nextest does build because of:

2023-04-29T08:03:36.5411530Z Compiling log v0.4.17
2023-04-29T08:03:36.5412100Z error[E0432]: unresolved import linux_raw_sys::ioctl
2023-04-29T08:03:36.5412710Z --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1285ae84e5963aae/rustix-0.37.17/src/backend/libc/io/syscalls.rs:384:24
2023-04-29T08:03:36.5413150Z |
2023-04-29T08:03:36.5413830Z 384 | use linux_raw_sys::ioctl::EXT4_IOC_RESIZE_FS;
2023-04-29T08:03:36.5414380Z | could not find ioctl in linux_raw_sys
2023-04-29T08:03:36.5414590Z
2023-04-29T08:03:36.5414840Z For more information about this error, try rustc --explain E0432.
2023-04-29T08:03:36.5415280Z error: could not compile rustix due to previous error
2023-04-29T08:03:36.5415730Z warning: build failed, waiting for other jobs to finish...

https://github.com/nextest-rs/nextest/issues/862